SchoolSysteam/Controllers/PayrollItemController.cs
using SchoolSysteam.Entitys;
using SchoolSystem.Core;
using SchoolSystem.ViewModel.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSysteam.Controllers
{
    public class PayrollItemController : Controller
    {
        DB_A40639_SchoolSystemEntities un = new DB_A40639_SchoolSystemEntities();

        // GET: PayrollItem
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {
            int GroupId = Convert.ToInt32(Request.Cookies["GroupId"].Value);
            var Actions = un.AppActions.Where(a => a.AppController.ControllerName == "PayrollItemController" && a.ActionName == "Index1").Select(a => a.Id).FirstOrDefault();
            var ActionsAddEdit = un.AppActions.Where(a => a.AppController.ControllerName == "PayrollItemController" && a.ActionName == "Create").Select(a => a.Id).FirstOrDefault();
            var ActionsDelete = un.AppActions.Where(a => a.AppController.ControllerName == "PayrollItemController" && a.ActionName == "Delete").Select(a => a.Id).FirstOrDefault();

            var IndexRole = un.RolesGroups.Where(a => a.Groups_Id == GroupId && a.Roles_Id == Actions).Count();
            ViewBag.EditAddRole = un.RolesGroups.Where(a => a.Groups_Id == GroupId && a.Roles_Id == ActionsAddEdit).Count();
            ViewBag.DeleteRole = un.RolesGroups.Where(a => a.Groups_Id == GroupId && a.Roles_Id == ActionsDelete).Count();

            if (IndexRole != 0)
            {

                var model = "SP_GetAllPayrollItem".ExecuParamsSqlOrStored(false).AsList<PayrollItemVM>();
                return View(model);
            }
            else
            {
                return View();
            }
        }


        public ActionResult Create()
        {
            PayrollItemVM Obj = new PayrollItemVM();

            return View(Obj);
        }
        [HttpPost]
        public ActionResult Create(PayrollItemVM model)
        {

            model.NameEn = model.NameAr;
            var data = "SP_AddPayrollItem".ExecuParamsSqlOrStored(false, "NameAr".KVP(model.NameAr),
                "NameEn".KVP(model.NameEn),
                "Type".KVP(model.Type),
                "Value".KVP(model.Value),
                "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {


                TempData["success"] = "<script>alert(' تم الاضافه بنجاح');</script>";
                return RedirectToAction("Index1");

            }
            else
                TempData["success"] = "<script>alert(' لم يتم الاضافه ');</script>";

            return RedirectToAction("Index1");

        }


        public ActionResult Edit(int id = 0)
        {

            var model = "SP_SelectPayrollItemById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<PayrollItemVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }



        [HttpGet]
        public ActionResult Delete(int id)
        {
            PayrollItemVM obj = new PayrollItemVM();
            obj.Id = id;
            return PartialView("~/Views/PayrollItem/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeletePayrollItem".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }

    }
}

SchoolSysteam/Views/PayrollItem/Create.cshtml
@model SchoolSystem.ViewModel.ViewModel.PayrollItemVM




<div class="card-box">
    <h4 class="m-t-0 header-title">@ViewBag.Title</h4>
</div>
<div class="card-box">
    @using (Html.BeginForm("Create", "PayrollItem", FormMethod.Post, new { @style = "margin-bottom: 11px;", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(i => i.Id);

        <div class="form-group row">
            <label class="col-2 col-form-label">اسم البند</label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.NameAr, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">القيمة </label>
            <div class="col-10">
                @Html.TextBoxFor(i => i.Value, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-2 col-form-label">النوع </label>
            <div class="col-10">
                <select id="Type" class="form-control " >
                    <option  value="1">مستحق</option>
                    <option value="0" >غير مستحق</option>
                </select>
                </div>
            </div>

                <div class="col-lg-12" style="text-align: left;">
                    <button type="submit" class="btn btn-success btn-rounded w-md waves-effect waves-light m-b-5">حفظ</button>
                    <a href="@Url.Action("Index1","PayrollItem")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">عودة</a>
                </div>
                }
                <div class="clearfix"></div>
            </div>

SchoolSysteam/Views/PayrollItem/Delete.cshtml
@model SchoolSystem.ViewModel.ViewModel.PayrollItemVM

                           
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> حذف  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

SchoolSysteam/Views/PayrollItem/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Raw(TempData["success"])
<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> بنود الرواتب</h4>

                    <a id="AddNew" href="@Url.Action("Create","PayrollItem")" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" style="float: left;">        اضافة جديد   </a>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/AjaxJS/PayrollItem.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            PayrollItem.init();

        })

    </script>
}

SchoolSysteam/Views/PayrollItem/Search.cshtml
@model IEnumerable<SchoolSystem.ViewModel.ViewModel.PayrollItemVM>
    @{ 
        Layout = null;
    }

@if (Model != null)
{
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" style="width:1000px;" width="100%">
                <thead style="background-color:#3bafda;color:white;">
                    <tr>
                        <th>التسلسل</th>
                        <th>اسم البند</th>
                        <th>النوع</th>
                        <th>القيمة</th>
                       

                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.NameAr</td>
                        @if (item.Type == 1)
                        {
                        <td>مستحق</td>   }
                        else
                        {
                            <td>غير مستحق</td>
                        }
                        <td>@item.Value</td>

                        
                       @if (ViewBag.EditAddRole != 0)
                        {
                    <td><a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-success   waves-effect waves-light m-b-0"><i class="ti-pencil"></i></a></td>
                        }
                        @if (ViewBag.DeleteRole != 0)
                        {
                        <td>
                            <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.Id)">  <i class="ti-trash"></i></button>

                        </td>
                        }

                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
}
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>